export const italianProvinces = [
  { code: "AG", label: "Agrigento (AG)", region: "Sicilia" },
  { code: "AL", label: "Alessandria (AL)", region: "Piemonte" },
  { code: "AN", label: "Ancona (AN)", region: "Marche" },
  { code: "AO", label: "Aosta (AO)", region: "Valle d'Aosta" },
  { code: "AP", label: "Ascoli Piceno (AP)", region: "Marche" },
  { code: "AQ", label: "L'Aquila (AQ)", region: "Abruzzo" },
  { code: "AR", label: "Arezzo (AR)", region: "Toscana" },
  { code: "AT", label: "Asti (AT)", region: "Piemonte" },
  { code: "AV", label: "Avellino (AV)", region: "Campania" },
  { code: "BA", label: "Bari (BA)", region: "Puglia" },
  { code: "BT", label: "Barletta-Andria-Trani (BT)", region: "Puglia" },
  { code: "BL", label: "Belluno (BL)", region: "Veneto" },
  { code: "BN", label: "Benevento (BN)", region: "Campania" },
  { code: "BG", label: "Bergamo (BG)", region: "Lombardia" },
  { code: "BI", label: "Biella (BI)", region: "Piemonte" },
  { code: "BO", label: "Bologna (BO)", region: "Emilia-Romagna" },
  { code: "BZ", label: "Bolzano (BZ)", region: "Trentino-Alto Adige" },
  { code: "BS", label: "Brescia (BS)", region: "Lombardia" },
  { code: "BR", label: "Brindisi (BR)", region: "Puglia" },
  { code: "CA", label: "Cagliari (CA)", region: "Sardegna" },
  { code: "CL", label: "Caltanissetta (CL)", region: "Sicilia" },
  { code: "CB", label: "Campobasso (CB)", region: "Molise" },
  { code: "CI", label: "Carbonia-Iglesias (CI)", region: "Sardegna" },
  { code: "CE", label: "Caserta (CE)", region: "Campania" },
  { code: "CT", label: "Catania (CT)", region: "Sicilia" },
  { code: "CZ", label: "Catanzaro (CZ)", region: "Calabria" },
  { code: "CH", label: "Chieti (CH)", region: "Abruzzo" },
  { code: "CO", label: "Como (CO)", region: "Lombardia" },
  { code: "CS", label: "Cosenza (CS)", region: "Calabria" },
  { code: "CR", label: "Cremona (CR)", region: "Lombardia" },
  { code: "KR", label: "Crotone (KR)", region: "Calabria" },
  { code: "CN", label: "Cuneo (CN)", region: "Piemonte" },
  { code: "EN", label: "Enna (EN)", region: "Sicilia" },
  { code: "FM", label: "Fermo (FM)", region: "Marche" },
  { code: "FE", label: "Ferrara (FE)", region: "Emilia-Romagna" },
  { code: "FI", label: "Firenze (FI)", region: "Toscana" },
  { code: "FG", label: "Foggia (FG)", region: "Puglia" },
  { code: "FC", label: "Forli-Cesena (FC)", region: "Emilia-Romagna" },
  { code: "FR", label: "Frosinone (FR)", region: "Lazio" },
  { code: "GE", label: "Genova (GE)", region: "Liguria" },
  { code: "GO", label: "Gorizia (GO)", region: "Friuli-Venezia Giulia" },
  { code: "GR", label: "Grosseto (GR)", region: "Toscana" },
  { code: "IM", label: "Imperia (IM)", region: "Liguria" },
  { code: "IS", label: "Isernia (IS)", region: "Molise" },
  { code: "SP", label: "La Spezia (SP)", region: "Liguria" },
  { code: "LT", label: "Latina (LT)", region: "Lazio" },
  { code: "LE", label: "Lecce (LE)", region: "Puglia" },
  { code: "LC", label: "Lecco (LC)", region: "Lombardia" },
  { code: "LI", label: "Livorno (LI)", region: "Toscana" },
  { code: "LO", label: "Lodi (LO)", region: "Lombardia" },
  { code: "LU", label: "Lucca (LU)", region: "Toscana" },
  { code: "MC", label: "Macerata (MC)", region: "Marche" },
  { code: "MN", label: "Mantova (MN)", region: "Lombardia" },
  { code: "MS", label: "Massa-Carrara (MS)", region: "Toscana" },
  { code: "MT", label: "Matera (MT)", region: "Basilicata" },
  { code: "ME", label: "Messina (ME)", region: "Sicilia" },
  { code: "MI", label: "Milano (MI)", region: "Lombardia" },
  { code: "MO", label: "Modena (MO)", region: "Emilia-Romagna" },
  { code: "MB", label: "Monza e Brianza (MB)", region: "Lombardia" },
  { code: "NA", label: "Napoli (NA)", region: "Campania" },
  { code: "NO", label: "Novara (NO)", region: "Piemonte" },
  { code: "NU", label: "Nuoro (NU)", region: "Sardegna" },
  { code: "OR", label: "Oristano (OR)", region: "Sardegna" },
  { code: "PD", label: "Padova (PD)", region: "Veneto" },
  { code: "PA", label: "Palermo (PA)", region: "Sicilia" },
  { code: "PR", label: "Parma (PR)", region: "Emilia-Romagna" },
  { code: "PV", label: "Pavia (PV)", region: "Lombardia" },
  { code: "PG", label: "Perugia (PG)", region: "Umbria" },
  { code: "PU", label: "Pesaro e Urbino (PU)", region: "Marche" },
  { code: "PE", label: "Pescara (PE)", region: "Abruzzo" },
  { code: "PC", label: "Piacenza (PC)", region: "Emilia-Romagna" },
  { code: "PI", label: "Pisa (PI)", region: "Toscana" },
  { code: "PT", label: "Pistoia (PT)", region: "Toscana" },
  { code: "PN", label: "Pordenone (PN)", region: "Friuli-Venezia Giulia" },
  { code: "PZ", label: "Potenza (PZ)", region: "Basilicata" },
  { code: "PO", label: "Prato (PO)", region: "Toscana" },
  { code: "RG", label: "Ragusa (RG)", region: "Sicilia" },
  { code: "RA", label: "Ravenna (RA)", region: "Emilia-Romagna" },
  { code: "RC", label: "Reggio Calabria (RC)", region: "Calabria" },
  { code: "RE", label: "Reggio Emilia (RE)", region: "Emilia-Romagna" },
  { code: "RI", label: "Rieti (RI)", region: "Lazio" },
  { code: "RN", label: "Rimini (RN)", region: "Emilia-Romagna" },
  { code: "RM", label: "Roma (RM)", region: "Lazio" },
  { code: "RO", label: "Rovigo (RO)", region: "Veneto" },
  { code: "SA", label: "Salerno (SA)", region: "Campania" },
  { code: "SS", label: "Sassari (SS)", region: "Sardegna" },
  { code: "SV", label: "Savona (SV)", region: "Liguria" },
  { code: "SI", label: "Siena (SI)", region: "Toscana" },
  { code: "SR", label: "Siracusa (SR)", region: "Sicilia" },
  { code: "SO", label: "Sondrio (SO)", region: "Lombardia" },
  { code: "TA", label: "Taranto (TA)", region: "Puglia" },
  { code: "TE", label: "Teramo (TE)", region: "Abruzzo" },
  { code: "TR", label: "Terni (TR)", region: "Umbria" },
  { code: "TO", label: "Torino (TO)", region: "Piemonte" },
  { code: "OG", label: "Ogliastra (OG)", region: "Sardegna" },
  { code: "TP", label: "Trapani (TP)", region: "Sicilia" },
  { code: "TN", label: "Trento (TN)", region: "Trentino-Alto Adige" },
  { code: "TV", label: "Treviso (TV)", region: "Veneto" },
  { code: "TS", label: "Trieste (TS)", region: "Friuli-Venezia Giulia" },
  { code: "UD", label: "Udine (UD)", region: "Friuli-Venezia Giulia" },
  { code: "VA", label: "Varese (VA)", region: "Lombardia" },
  { code: "VE", label: "Venezia (VE)", region: "Veneto" },
  { code: "VB", label: "Verbano-Cusio-Ossola (VB)", region: "Piemonte" },
  { code: "VC", label: "Vercelli (VC)", region: "Piemonte" },
  { code: "VR", label: "Verona (VR)", region: "Veneto" },
  { code: "VV", label: "Vibo Valentia (VV)", region: "Calabria" },
  { code: "VI", label: "Vicenza (VI)", region: "Veneto" },
  { code: "VT", label: "Viterbo (VT)", region: "Lazio" }
] as const;

export const italianProvinceCodes = italianProvinces.map((province) => province.code);
export const italianProvinceMap = new Map(
  italianProvinces.map((province) => [province.code, province])
);

export function getItalianProvince(code: string) {
  return italianProvinceMap.get(code as ItalianProvinceCode);
}

export type ItalianProvinceCode = (typeof italianProvinces)[number]["code"];
